import anthropic
from config import ANTHROPIC_API_KEY, CLAUDE_MODEL


client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)


def summarize_articles(articles: list[dict]) -> str:
    """
    Takes a list of article dicts and returns a formatted digest summary
    generated by Claude.
    """
    if not articles:
        return "No new articles to summarize."

    # Build a readable block of articles to send to Claude
    articles_text = ""
    for i, article in enumerate(articles, 1):
        articles_text += f"""
Article {i}:
Source: {article['source']}
Title: {article['title']}
Summary: {article['summary']}
Link: {article['link']}
---
"""

    prompt = f"""You are a helpful news assistant. Below are some recent news articles fetched from RSS feeds.

Please write a concise, well-structured news digest that:
- Groups articles by topic or theme if possible
- Gives a 1-2 sentence summary for each article
- Includes the source name next to each item
- Is easy to read in an email
- Ends with a "Full Links" section listing all article URLs

Here are the articles:
{articles_text}

Write the digest now:"""

    print("Sending articles to Claude for summarization...")

    message = client.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=1024,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )

    return message.content[0].text